SRF_ENABLED = True
SECRET_KEY = 'you-will-never-guess'

MYSQL_DATABASE_HOST ='172.17.0.6'
MYSQL_DATABASE_PORT =3306
MYSQL_DATABASE_USER ='opencart-mobile'
MYSQL_DATABASE_PASSWORD ='secret'
MYSQL_DATABASE_DB ='fsz_opencart'
#MYSQL_DATABASE_CHARSET='UTF-8'

